In [55]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [56]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder , OrdinalEncoder

In [57]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue"],
    "Size": ["Small", "Medium", "Large", "Small", "Large"],
    "Level": ["Low", "Medium", "High", "Medium", "Low"],
    "City": ["Chennai", "Delhi", "Mumbai", "Delhi", "Chennai"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes"]
})

# LabelEncoder

In [58]:
label_encoder = LabelEncoder()

In [74]:
label_encoder.fit_transform(df["Purchased"])  # label encoder accepts omly 1 Dimensional : 1 COLUMN
#[ internally it is sorting the values by ascii and assigining the numbers]]

array([1, 0, 1, 0, 1])

In [75]:
label_encoder.fit_transform(df[["Purchased"]]) #here we are passing 2D but internally it is checking shape (5,2)
#shape should be (5,1) - internally it is checking for the shape

c:\Users\Mahammad Furkhan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 0, 1])

In [76]:
res = df[["Purchased"]]
res.shape

(5, 1)

In [62]:
# label_encoder.fit_transform(df["Color","Purchased"]) # Display the error 2D

transforming

In [ ]:
label_encoder.transform(["Yes",])  

array([1])

In [63]:
# label_encoder.transform([["Yes","Yes"]])  
#ValueError: y should be a 1d array, got an array of shape (1, 2) instead.

In [64]:
# label_encoder.transform([["Yess"]])   #Yess is not trained in Label-encoder fit_transform not learnt this value
# ValueError: y contains previously unseen labels: 'Yess'


# OneHotEncoder

In [77]:
one_hot_encoder = OneHotEncoder()

In [ ]:
one_hot_encoder.fit_transform

# OrdinalEncoder

In [65]:
encode = OrdinalEncoder()

In [66]:
values = encode.fit_transform(df)

In [67]:
encode = OrdinalEncoder(categories=[["Blue","Green","Red"],
                                   ["Small", "Medium", "Large"],
                                   ["Low", "Medium", "High"],
                                   ["Chennai", "Delhi", "Mumbai"],
                                   ["Yes","No"]])
values = encode.fit_transform(df) #df has 5 columns so while transforming also we should pass all the columns
values

array([[2., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1.],
       [1., 2., 2., 2., 0.],
       [2., 0., 1., 1., 1.],
       [0., 2., 0., 0., 0.]])

Blue - 0  
Green - 1  
Red - 0  

In [68]:
# #ValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input.
# encode.transform([["Red"]]) 


#how many columns we have in our original data frame while transforming also we should pass the same number of columns.
encode.transform([["Red","Small","Low","Chennai","Yes"]])

c:\Users\Mahammad Furkhan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2., 0., 0., 0., 0.]])

In [69]:
# encode = OrdinalEncoder(categories=[["Blue","Green","Red"]],handle_unknown="use_encoded_value")
# values = encode.fit_transform(df[["Color"]])
# encode.transform([["Orange"]])

#TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.


In [70]:
# encode = OrdinalEncoder(categories=[["Blue","Green","Red"]],handle_unknown="use_encoded_value",unknown_value=0)
# values = encode.fit_transform(df[["Color"]])
# encode.transform([["Orange"]])

'''ValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.'''

# Defaulty unknown_value= none : if we assign unkown_value = 0 then Valueerror cox already Blue has Assigned with o

'ValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.'

In [71]:
encode = OrdinalEncoder(categories=[["Blue","Green","Red"]],handle_unknown="use_encoded_value",unknown_value=-1)
values = encode.fit_transform(df[["Color"]])
encode.transform([["Orange"]])


# in this we are assiging which are not assigned earlier which is unknown_value=-1

c:\Users\Mahammad Furkhan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.]])